### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by PythonCook** [gered/clj-hl7-fhir#2]
So I love the library and would really like to use it, but I'm getting a compiler error when I use the clj-hl7-fhir.core namespace. 

user=> (use 'clj-hl7-fhir.core)

CompilerException java.lang.NoClassDefFoundError: IllegalName: compile__stub.clj
_http.headers.clj-http.headers/HeaderMap, compiling:(clj_http/headers.clj:105:1)

**Comment by gered** [comment]
Guessing it's a dependency issue. clj-hl7-fhir has not been updated in a good long while, so it's dependencies are out of date and probably causing some conflicts with something else that depends on clj-http in your project. I'll see about releasing a new version with updated dependencies shortly and hopefully that might fix the problem for you (I suppose you could also try adding some `:exclusions` to your project.clj too in the mean time if you prefer not to wait).

**Comment by gered** [comment]
Ok, try updating to the latest version I just pushed and let me know if you still encounter any issues.

`[clj-hl7-fhir "0.3.1"]`

**Comment by PythonCook** [comment]
Awesome! Thank you so much!
